#!/bin/sh /etc/rc.common

START=99
STOP=11

board_name() {
    [ -e /tmp/sysinfo/board_name ] && cat /tmp/sysinfo/board_name || echo "generic"
}

start() {
    local board=$(board_name)
    case "$board" in
        nsy,g68-plus)
            if [ -e /sys/class/net/ra0 ]; then
                wifi up
                sleep 5
                echo f > /sys/class/net/ra0/queues/rx-0/rps_cpus
                echo f > /sys/class/net/rax0/queues/rx-0/rps_cpus
                echo 10000 > /proc/sys/net/core/netdev_budget
            fi
            ;;
        *)
            return 1
            ;;
    esac
}
